config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root 'homes#index'
  resources :homes, only: :index

  get '/lyrics/ranking', to: 'lyrics#ranking'
  resources :lyrics, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:index]
    member do
      get :explain
    end
  end

  resources :users, only: [:show] do
    member do
      get :favorites, to: 'users#show_favorites', as: 'user_favorites'
      get :show_followers
      get :show_following
    end
  end

  post '/users/guest_sign_in', to: 'users#guest_sign_in'
  post '/users/guest_admin_sign_in', to: 'users#guest_admin_sign_in'

  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/lyric.rb
class Lyric < ApplicationRecord
  validates :phrase, presence: true, length: { maximum: 20 }
  validates :detail, presence: true
  has_one :artist, dependent: :destroy
  has_one :song, dependent: :destroy
  accepts_nested_attributes_for :artist, allow_destroy: true
  accepts_nested_attributes_for :song, allow_destroy: true
  belongs_to :user
  has_many :lyrics_feelings, dependent: :destroy
  has_many :feelings, through: :lyrics_feelings, source: :feeling
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  is_impressionable counter_cache: true
  validates :phrase, presence: true
  validates :detail, presence: true

  scope :recently_created, -> { where('created_at >= ?', 1.month.ago) }
  scope :ranked, -> { order(impressions_count: :desc) }
  scope :with_associations, -> { includes(:song, :artist, :comments, user: :user_profile) }

  def self.ransackable_attributes(auth_object = nil)
    %w[id phrase]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[artist song feelings lyrics_feelings]
  end

  def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and lyric_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        lyric_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(lyric_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      lyric_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  before_action :authenticate_user!, only: %i[new create]
  before_action :set_lyric, only: %i[show edit update destroy explain]
  
  def index
    @q = Lyric.ransack(params[:q].try(:to_unsafe_h))
    @feelings = Feeling.all
    @lyrics = @q.result.includes(:artist, :song, :feelings, :lyrics_feelings).order(created_at: :desc)
    @favorite_count = Favorite.where(lyric_id: @lyrics.map(&:id)).group(:lyric_id).count
  end

  def new
    @lyric = Lyric.new
    @lyric.build_song
    @lyric.build_artist
  end
  
  def create
    @lyric = Lyric.new(lyric_params)
    @lyric.user_id = current_user.id
    if @lyric.save
      redirect_to lyrics_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lyric.update(lyric_params)
      redirect_to lyrics_path
    else
      render :edit
    end
  end
  
  def show
    if user_signed_in?
      @favorite = current_user.favorites.find_by(lyric_id: @lyric.id)
    end
    impressionist(@lyric, nil, unique: [:ip_address]) 
    @comments = @lyric.comments
    @comment = @lyric.comments.build
    @tracks = []
    song = @lyric.song.title
    artist = @lyric.artist.name
    tracks = RSpotify::Track.search("#{song} #{artist}")
    tracks.each do |track|
      url = track.preview_url
      @tracks << { lyric: @lyric, url: url, track: track }
    end
    @favorite_count = Favorite.where(lyric_id: @lyric.id).group(:lyric_id).count
  end

  def destroy
    @lyric.destroy
    redirect_to lyrics_path
  end

  def ranking
    @rank_lyrics = Lyric.recently_created.ranked.with_associations.limit(5)
    @lyric_comments_count = Comment.where(lyric_id: @rank_lyrics.map(&:id)).group(:lyric_id).count
    @tracks = []
    @rank_lyrics.each do |rank_lyric|
      song = rank_lyric.song.title
      artist = rank_lyric.artist.name
      tracks = RSpotify::Track.search("#{song} #{artist}")
      tracks.each do |track|
        url = track.preview_url
        @tracks << { lyric: rank_lyric, url: url, track: track }
      end
    end
  end

  require "openai"

  def explain
    @phrase = @lyric.phrase
    @song = @lyric.song.title
    @artist = @lyric.artist.name

    client = OpenAI::Client.new(access_token: ENV["OPENAI_API_KEY"])
    response = client.chat(
        parameters: {
          model: "gpt-3.5-turbo-0613",
          messages: [
            { role: "system", content: "曲名と歌手名とその曲に含まれる歌詞を伝えるので、その歌詞に込められた意図を推察して教えてください。" },
            { role: "system", content: "100字以内で回答してください。"},
            { role: "system", content: "回答には、「他に何か別の質問やトピックについてお知りになりたいことがあれば、どうぞお知らせください。」のような、次の質問を促すような文言は含めないでください。" },
            { role: "system", content: "「データベースには含まれておりません」という回答は不要です。" },
            { role: "system", content: "「この歌詞の解釈は、個人によって異なるかもしれません」という回答は不要です。" },
            { role: "system", content: "「ただし、これは一つの解釈であり、個人によって解釈が異なる可能性もあります」という回答は不要です。" },
            { role: "system", content: "「具体的な解釈は聴く人によって異なる可能性があるので、個々の解釈は多様であることに留意してください」という回答は不要です。"},
            { role: "system", content: "「具体的な意図は個人の解釈によって異なるかもしれません」という旨の回答は不要です。"},
            { role: "user", content: "#{@artist}の#{@song}という曲について、#{@phrase}という歌詞があります。その歌詞に込められた意図を推察して教えてください。" },
            { role: "user", content: "もし、「#{@artist}」の「#{@song}」や「#{@phrase}」といった楽曲や歌詞についての情報があなたのデータベースには含まれていない場合は、『歌詞についての説明が作成できませんでした』とだけ答え、その他に余計な文章を答えないでください。" },
            { role: "user", content: "回答は、「この歌詞は」で始めてください。" },
          ],
        },
      )

    @explain = response.dig("choices", 0, "message", "content")
  end

  private

  def lyric_params
    params.require(:lyric).permit(:phrase, :detail, song_attributes: [:title], artist_attributes: [:name], feeling_ids: [] )
  end

  def set_lyric
    @lyric = Lyric.includes(:favorites, :comments, :song, :artist).find(params[:id])
  end
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/views/lyrics/_form.html.erb
<%= form_with(model: @lyric, local: true, class: "max-w-md mx-auto") do |f| %>
  <% if @lyric.errors.any? %>
    <div id="error_explanation" class="bg-red-100 text-red-600 px-4 py-3 mb-4 rounded-lg">
      <h2><%= @lyric.errors.count %> 件のエラーがあります。</h2>
      <ul>
        <% @lyric.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="text-gray-600">
    <div class="lyric_phrase mb-4">
      <%= f.label :phrase, class: "block " %>
      <%= f.text_field :phrase, placeholder: t('view.place_holder.phrase'), class: "block w-full border rounded-lg px-4 py-2" %>
    </div>
    <div class="lyric_detail mb-4">
      <%= f.label :detail, class: "block" %>
      <%= f.text_area :detail, placeholder: t('view.place_holder.detail'), class: "block w-full border rounded-lg px-4 py-2" %>
    </div>
    <div class="song_title mb-4">
      <%= f.fields_for :song do |s| %>
        <%= s.label :title, class: "block" %>
        <%= s.text_field :title, placeholder: t('view.place_holder.song_title'), class: "block w-full border rounded-lg px-4 py-2" %>
      <% end %>
    </div>
    <div class="artist_name mb-4">
      <%= f.fields_for :artist do |a| %>
        <%= a.label :name, class: "block" %>
        <%= a.text_field :name, placeholder: t('view.place_holder.artist_name'), class: "block w-full border rounded-lg px-4 py-2" %>
      <% end %>
    </div>
    <div class="feeling_sort mb-4">
      <% Feeling.all.each do |feeling| %>
        <label class="block items-center">
          <%= f.check_box :feeling_ids, { multiple: true, checked: @lyric.feeling_ids.include?(feeling.id), disabled: feeling[:disabled], include_hidden: false }, feeling[:id], class: "form-checkbox" %>
          <%= feeling.sort %>
        </label>
      <% end %>
    </div>
    <div class="mb-4">
      <button class="custom-button mt-4">
        <%= f.submit t('view.lyric.create') %>
      </button>
    </div>
  <% end %>
</div>

<%= link_to t('view.lyric.back'), lyrics_path, class: "block mt-4 text-blue-500 hover:underline" %>

app/views/lyrics/edit.html.erb
<%= render 'form' %>

app/views/lyrics/explain.html.erb
<h4 class="text-gray-600 mb-4">AIによる歌詞解説</h4>
<div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
  <p class ="ml-4 mr-4 mt-4 mb-4 text-gray-600 text-left"><%= @explain %></p>
</div>

app/views/lyrics/index.html.erb
<div class="container mx-auto py-8">
  <div class="search_ranking_button flex flex-col items-center md:flex-row justify-center md:justify-between mb-4">
    <%= search_form_for @q, method: :get, class: "flex flex-col md:flex-row items-center" do |f| %>
      <%= f.search_field :phrase_cont, placeholder: t('view.place_holder.phrase_search'), class: "w-full md:w-auto mb-2 md:mb-0 md:mr-2 px-4 py-2 rounded-lg shadow-sm" %>
      <%= f.search_field :song_title_cont, placeholder: t('view.place_holder.song_search'), class: "w-full md:w-auto mb-2 md:mb-0 md:mr-2 px-4 py-2 rounded-lg shadow-sm" %>
      <%= f.search_field :artist_name_cont, placeholder: t('view.place_holder.artist_search'), class: "w-full md:w-auto mb-2 md:mb-0 md:mr-2 px-4 py-2 rounded-lg shadow-sm" %>
      <%= f.select :feelings_id_eq, options_from_collection_for_select(@feelings, :id, :sort), { include_blank: t('view.place_holder.feeling_search') }, class: "w-full md:w-auto mb-2 md:mb-0 md:mr-2 px-4 py-2 rounded-lg shadow-sm" %>
      <button class="custom-button mb-4 mt-4">
        <%= f.submit t('view.lyric.search'), class: "w-full md:w-auto px-4 py-2 rounded-lg text-white font-semibold shadow-sm" %>
      </button>
    <% end %>
    <button class="custom-button">
      <%= button_to t('view.lyric.ranking'), lyrics_ranking_path, method: :get, class: "w-full md:w-auto px-4 py-2 rounded-lg bg-gray-500 text-white font-semibold shadow-sm" %>
    </button>
  </div>
  <% @lyrics.each do |lyric| %>
    <div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
      <div class="flex items-center justify-start mb-4 w-full">
        <%= link_to user_path(lyric.user.id), class: "inline-flex items-center ml-2" do %>
          <% if lyric.user.user_profile.icon && lyric.user.user_profile.icon.url %>
            <%= image_tag(lyric.user.user_profile.icon.url, class: "rounded-circle", size: "25x25") %>
          <% else %>
            <%= image_tag("default.png", class: "rounded-circle", size: "25x25") %>
          <% end %>
          <p class="ml-2"><%= lyric.user.user_profile.name %></p>
        <% end %>
        <span class="ml-2 text-xs text-gray-500"><%= lyric.created_at.strftime("%Y-%m-%d %H:%M") %></span>
      </div>
      <p class="lyric_phrase_test px-2 py-1 bg-gray-100 rounded-full text-sm text-gray-500"> <%= lyric.phrase %></p>
      <p class="mt-4 mr-2 ml-2 text-gray-600"><%= truncate(lyric.detail, length: 20) %></p>
      <p class="mt-2 mr-2 ml-2 text-gray-600"><%= lyric.song.title %> / <%= lyric.artist.name %></p>
      <p class="test_feeling mt-2 mb-2">
        <% lyric.feelings.each do |feeling| %>
          <span class="tag-pink px-2 py-1 rounded-full text-sm text-gray-500">
            <%= feeling.sort %>
          </span>
        <% end %>
      </p>
      <span class="text-xs text-gray-400"><%= @favorite_count[lyric.id] || 0 %>♡</span>
      <span class='mb-4', id='detail_link'><%= link_to t('view.lyric.show'), lyric_path(lyric.id) %></span>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <button class="custom-button mt-4">
      <%= button_to t('view.lyric.new'), new_lyric_path, method: :get, class: "w-full px-4 py-2 rounded-lg text-white font-semibold shadow-sm" %>
    </button>
  <% end %>
</div>

app/views/lyrics/new.html.erb
<%= render 'form' %>

app/views/lyrics/ranking.html.erb
<div class="container mx-auto py-8">
  <h2 class="text-2xl mb-4 text-gray-600">月間閲覧数ランキング</h2>
  <div class="grid grid-cols-1 justify-center gap-4">
    <% n = 1 %>
    <% @rank_lyrics.each do |t| %>
      <div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
        <div class="flex items-center justify-start mb-4 w-full">
          <p><%= "第#{n}位"%></p>
          <%= link_to user_path(t.user.id), class: "inline-flex items-center ml-2" do %>
            <% if t.user.user_profile.icon && t.user.user_profile.icon.url %>
              <%= image_tag(t.user.user_profile.icon.url, class: 'rounded-circle', size: '25x25') %>
            <% else %>
              <%= image_tag('default.png', class: 'rounded-circle', size: '25x25') %>
            <% end %>
            <p class="ml-2"><%= t.user.user_profile.name %></p>
          <% end %>
        </div>
        <p class="px-3 py-2 bg-gray-100 rounded-full text-base text-gray-600"><%= "#{t.phrase}" %></p>
        <p class="ml-2 mr-2 mt-4 text-gray-600"><%= "#{truncate(t.detail, length: 10)}" %></p>
        <p class="ml-2 mr-2 mt-2 text-gray-600"><%= "#{t.song.title}  /  #{t.artist.name}" %></p>
        <p class="mt-4 text-gray-600">
          <%= "#{t.impressions_count} Views" %>
          <%= link_to "Comments(#{@lyric_comments_count[t.id] || 0})", lyric_path(t.id) %>
        </p>
        <br>
        <% track = @tracks.find { |t_for_track| t_for_track[:lyric] == t } %>
        <div class="flex items-center justify-center mb-4">
        <% if track && track[:url] %>
          <audio id='player_<%= n %>' src='<%= track[:url] %>' controls class="mr-4"></audio>
          <p class="ml-2"><%= link_to 'Play Full', track[:track].external_urls['spotify'], target: '_blank' %></p>
          <script>
            document.getElementById('player_<%= n %>').volume = 0.1;
          </script>
        <% else %>
          <p>No preview available</p>
        <% end %>
      </div>
      </div>
      <% n += 1 %>
    <% end %>
    <br>
  </div>
</div>

app/views/lyrics/show.html.erb
<div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
  <div class="flex items-center justify-start mb-4 w-full">
    <%= link_to user_path(@lyric.user.id), class: "inline-flex items-center ml-2" do %>
      <% if @lyric.user.user_profile.icon && @lyric.user.user_profile.icon.url %>
        <%= image_tag(@lyric.user.user_profile.icon.url, class: "rounded-circle", size: "25x25") %>
      <% else %>
        <%= image_tag("default.png", class: "rounded-circle", size: "25x25") %>
      <% end %>
      <p class="ml-2"><%= @lyric.user.user_profile.name %></p>
    <% end %>
    <span class="ml-2 text-xs text-gray-500"><%= @lyric.created_at.strftime("%Y-%m-%d %H:%M")  %></span>
  </div>
  <p class="lyric_phrase px-3 py-2 bg-gray-100 rounded-full text-base text-gray-600"><%= @lyric.phrase %></p>
  <p class="ml-2 mr-2 mt-4 text-gray-600"><%= @lyric.detail %></p>
  <p class="ml-2 mr-2 mt-2 text-gray-600"><%= @lyric.song.title %> / <%= @lyric.artist.name %></p>
  <p class="mt-4 mb-4">
  <% @lyric.feelings.each do |feeling| %>
    <span class="tag-pink px-2 py-1 rounded-full text-sm text-gray-500">
      <%= feeling.sort %>
    </span>
  <% end %>
  </p>

  <% track = @tracks.find { |t| t[:lyric] == @lyric } %>
  <div class="flex items-center justify-center">
    <% if track && track[:url] %>
      <p><audio id="player" src="<%= track[:url] %>" controls></audio></p>
      <p class="ml-3"><%= link_to 'Play Full', track[:track].external_urls['spotify'], target: '_blank' %></p>
      <script>
        document.getElementById('player').volume = 0.1;
      </script>
    <% else %>
      <p>No preview available</p>
      <p></p>
    <% end %>
  </div>
    <button class= "opacity-60 shadow bg-red-100 hover:bg-red-200 text-white py-1 px-2 rounded-lg mt-4 mb-4 text-xs">
      <%= link_to 'AI歌詞解説', explain_lyric_path(@lyric) %>
    </button>
  <% if user_signed_in? %>
    <% unless @lyric.user_id == current_user.id %>
      <% if @favorite.present? %>
        <div id="js-favorite-<%= @lyric.id %>">
          <%= render partial: 'favorites/destroy', locals: { favorite: @favorite, lyric: @lyric, favorite_count: @favorite_count } %>
        </div>
      <% else %>
        <div id="js-favorite-<%= @lyric.id %>">
          <%= render partial: 'favorites/create', locals: { favorite: @favorite, lyric: @lyric, favorite_count: @favorite_count } %>
        </div>
      <% end %>
    <% else %>
      <div class="flex space-x-4 items-center justify-center">
        <div id="test_edit">
          <span><%= link_to t('view.lyric.edit'), edit_lyric_path(@lyric.id) %></span>
        </div>
        <span><%= link_to t('view.lyric.destroy'), lyric_path(@lyric.id), method: :delete, id:'test_destroy', data: { confirm: t('view.lyric.destroy_confirm') } %></span>
        <%= link_to lyric_favorites_path(lyric_id: @lyric.id) do %>
          <span class="text-xs text-gray-400"><%= @favorite_count[@lyric.id] || 0 %>♡</span>
        <% end %>
      </div>
    <% end %> 
</div>  
    <%= render partial: 'comments/form', locals: { comment: @comment, lyric: @lyric } %>
  <% else %>
    <p><%= link_to t('view.lyric.login_required'), new_user_session_path %></p>
  <% end %>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, lyric: @lyric } %>
  </div>