config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root 'homes#index'
  resources :homes, only: :index

  get '/lyrics/ranking', to: 'lyrics#ranking'
  resources :lyrics, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:index]
    member do
      get :explain
    end
  end

  resources :users, only: [:show] do
    member do
      get :favorites, to: 'users#show_favorites', as: 'user_favorites'
      get :show_followers
      get :show_following
    end
  end

  post '/users/guest_sign_in', to: 'users#guest_sign_in'
  post '/users/guest_admin_sign_in', to: 'users#guest_admin_sign_in'

  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :lyric
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy index]
  before_action :set_lyric, only: %i[create destroy index]
  def index
    @favorites = @lyric.favorites
    @favorite_count = @favorites.where(lyric_id: @lyric.id).group(:lyric_id).count
  end
  
  def create
    unless current_user.favorites.exists?(lyric: @lyric)
      @favorite = current_user.favorites.create(lyric_id: params[:lyric_id])
      @lyric.create_notification_favorite!(current_user)
      update_favorite_count
    end  
  end

  def destroy
    @favorite = current_user.favorites.find_by(id: params[:id]).destroy
    update_favorite_count
  end

  private

  def set_lyric
    @lyric = Lyric.find(params[:lyric_id])
  end

  def update_favorite_count
    @favorite_count = Favorite.where(lyric_id: @lyric.id).group(:lyric_id).count
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_create.html.erb
<%= link_to "#{favorite_count[lyric.id] || 0}#{t('view.favorite.create')}", favorites_path(lyric_id: lyric.id), id: "js-favorite-#{lyric.id}", class: 'mx-auto', method: :post, remote: true, data: { turbolinks: false } %>

app/views/favorites/_destroy.html.erb
<%= link_to "#{favorite_count[lyric.id] || 0}#{t('view.favorite.destroy')}", favorite_path(id: favorite.id, lyric_id: lyric.id), id: "js-favorite-#{lyric.id}", class: 'mx-auto', method: :delete, remote: true, data: { turbolinks: false } %>

app/views/favorites/create.js.erb
$("#js-favorite-<%= @lyric.id %>").replaceWith("<%= j render 'favorites/destroy', favorite: @favorite, lyric: @lyric, favorite_count: @favorite_count %>");

app/views/favorites/destroy.js.erb
$("#js-favorite-<%= @lyric.id %>").replaceWith("<%= j render 'favorites/create', favorite: @favorite, lyric: @lyric, favorite_count: @favorite_count %>");

app/views/favorites/index.html.erb
<div class="container mx-auto py-8">
  <h2 class="text-2xl mb-8">お気に入りしてくれたユーザー</h2>
  <% if @favorites.any? %>
    <div class="grid grid-cols-1 gap-4">
      <% @favorites.each do |favorite| %>
        <div class="w-64 mx-auto bg-white shadow-md rounded-lg p-4">
          <%= link_to user_path(favorite.user.id) do %>
            <% if favorite.user.user_profile.icon && favorite.user.user_profile.icon.url %>
              <%= image_tag(favorite.user.user_profile.icon.url, class: "rounded-full w-12 h-12 mx-auto") %>
            <% else %>
              <%= image_tag("default.png", class: "rounded-full w-12 h-12 mx-auto") %>
            <% end %>
          <span class="block text-center mt-2"><%= favorite.user.user_profile.name %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-500 mt-4 text-center">まだお気に入りされていません。</p>
  <% end %>
</div>