config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root 'homes#index'
  resources :homes, only: :index

  get '/lyrics/ranking', to: 'lyrics#ranking'
  resources :lyrics, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:index]
    member do
      get :explain
    end
  end

  resources :users, only: [:show] do
    member do
      get :favorites, to: 'users#show_favorites', as: 'user_favorites'
      get :show_followers
      get :show_following
    end
  end

  post '/users/guest_sign_in', to: 'users#guest_sign_in'
  post '/users/guest_admin_sign_in', to: 'users#guest_admin_sign_in'

  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :timeoutable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_profile
  has_many :lyrics
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_lyrics, through: :favorites, source: :lyric
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.build_user_profile(name: "ゲスト")
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'guest-admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.build_user_profile(name: "ゲスト(管理者)")
      user.admin = true
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    guest_emails = ['guest@example.com', 'guest-admin@example.com']
  
    if guest_emails.include?(params[:user][:email].downcase)
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == "guest@example.com" || resource.email == "guest-admin@example.com"
      redirect_to lyrics_path, alert: "ゲストユーザーの更新・削除はできません。"
    end
  end
  # GET /resource/sign_up
  # def new
  #   super
  #   resource.build_user_profile if resource.user_profile.nil?
  # end

  # # POST /resource
  # def create
  #   super

  #   resource.build_user_profile
  #   resource.save
  # end

  # # GET /resource/edit
  # def edit
  #   super
  # end

  # # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show_favorites show_followers show_following]
  def show
    @user = User.find(params[:id]) 
    following_users = @user.following + [@user]
    @following_lyrics = Lyric.where(user_id: following_users).order(created_at: :desc)
    @lyric_ids = @following_lyrics.pluck(:id)
    @favorite_count = Favorite.where(lyric_id: @lyric_ids).group(:lyric_id).count
  end

  def show_favorites
    @favorites = current_user.favorites.order(created_at: :desc)
  end

  def show_followers
    @user = User.find(params[:id])
    @followers = @user.followers.all
  end

  def show_following
    @user = User.find(params[:id]) 
    @following = @user.following.all
  end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to lyrics_path, notice: "ゲストユーザーとしてログインしました"
  end

  def guest_admin_sign_in
    user = User.guest_admin
    sign_in user
    redirect_to lyrics_path, notice: 'ゲストユーザー（管理者）としてログインしました'
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id), local: false) do |f| %>
      <%= f.hidden_field :followed_id %>
      <button class="custom-button mt-4">
        <%= f.submit t('view.user.follow') %>
      </button>  
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete, local: false) do |f| %>
      <button class="custom-button mt-4">
        <%= f.submit t('view.user.unfollow') %>
      </button>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<p class="text-gray-600">User Page</p>
<% if current_user == @user %>
  <% if current_user.email != 'guest@example.com' && current_user.email != 'guest-admin@example.com' %>
    <%= link_to t('view.lyric.edit'), edit_user_registration_path %>
  <% end %>
<% end %>
<div class="mt-4 flex justify-center">
  <% if @user.user_profile.icon && @user.user_profile.icon.url %>
    <%= image_tag(@user.user_profile.icon.url, class: "rounded-circle", size: "50x50") %>
  <% else %>
    <%= image_tag("default.png", class: "rounded-circle", size: "50x50") %>
  <% end %>
</div>
<p class="mt-4 text-gray-600"><%= @user.user_profile.name %></p>
<p class="mt-4 ml-2 mr-2 text-gray-600"><%= @user.user_profile.introduction %></p>
<% if user_signed_in? && current_user != @user %>
  <%= render 'follow_form', user: @user %>
<% end %>
<% if current_user == @user %>
  <p class="mt-4 text-gray-600">メールアドレス: <%= @user.email %></p>
  <button class="custom-button mt-4">
    <%= button_to t('view.user.favorite'), user_favorites_user_path, method: :get %>
  </button>
  <button class="custom-button mt-4">
    <%= button_to t('view.user.follower'), show_followers_user_path, method: :get %>
  </button>
  <button class="custom-button mt-4">
    <%= button_to t('view.user.followed'), show_following_user_path, method: :get %>
  </button>
  <% if @following_lyrics.any? %>
    <div class="mt-8">
      <% @following_lyrics.each do |lyric| %>
        <div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
          <div class="flex items-center justify-start mb-4">
            <%= link_to user_path(lyric.user.id), class: "inline-flex items-center ml-2" do %>
              <%= image_tag(lyric.user.user_profile.icon&.url || "default.png", class: "rounded-circle", size: "25x25") %>
              <p class="ml-2"><%= lyric.user.user_profile.name %></p>
            <% end %>
            <span class="ml-2 text-xs text-gray-500"><%= lyric.created_at.strftime("%Y-%m-%d %H:%M")  %></span>
          </div>
          <p class="px-3 py-2 bg-gray-100 rounded-full text-base text-gray-600"><%= lyric.phrase %></p>
          <p class="mt-4 mr-2 ml-2 text-gray-600"><%= lyric.detail %></p>
          <p class="mr-2 ml-2 mt-2 text-gray-600"><%= "#{lyric.song.title} / #{lyric.artist.name}" %></p>
          <p class="mt-4 mb-4">
            <% lyric.feelings.each do |feeling| %>
              <span class="tag-pink px-2 py-1 rounded-full text-sm text-gray-500">
                <%= feeling.sort %>
              </span>
            <% end %>
          </p>
          <span class="text-xs text-gray-400"><%= @favorite_count[lyric.id] || 0 %>♡</span>
          <span><%= link_to t('view.lyric.show'), lyric_path(lyric.id) %></span>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <% if @user.lyrics.any? %>
    <div class="mt-8">
      <% @user.lyrics.each do |lyric| %>
        <div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
          <div class="flex items-center justify-start mb-4">
            <%= link_to user_path(lyric.user.id), class: "inline-flex items-center ml-2" do %>
              <%= image_tag(lyric.user.user_profile.icon&.url || "default.png", class: "rounded-circle", size: "25x25") %>
              <p class="ml-2"><%= lyric.user.user_profile.name %></p>
            <% end %>
            <span class="ml-2 text-xs text-gray-500"><%= lyric.created_at.strftime("%Y-%m-%d %H:%M")  %></span>
          </div>
          <p class="px-3 py-2 bg-gray-100 rounded-full text-base text-gray-600"><%= lyric.phrase %></p>
          <p class="mt-4"><%= lyric.detail %></p>
          <p><%= "#{lyric.song.title} / #{lyric.artist.name}" %></p>
          <p class="mt-4 mb-4">
            <% lyric.feelings.each do |feeling| %>
              <span class="tag-pink px-2 py-1 rounded-full text-sm text-gray-500">
                <%= feeling.sort %>
              </span>
            <% end %>
          </p>
          <span class="text-xs text-gray-400"><%= @favorite_count[lyric.id] || 0 %>♡</span>
          <span><%= link_to t('view.lyric.show'), lyric_path(lyric.id) %></span>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/users/show_favorites.html.erb
<div class="container mx-auto py-8">
  <h2 class="text-2xl mb-4 text-gray-600">お気に入り一覧</h2>
  <% if @favorites.any? %>
    <% @favorites.each do |favorite| %>
      <div class="w-full max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden mb-4 p-4">
        <div class="flex items-center justify-start mb-4 w-full">
          <%= link_to user_path(favorite.lyric.user.id), class: "inline-flex items-center ml-2" do %>
            <% if favorite.lyric.user.user_profile&.icon&.url %>
              <%= image_tag(favorite.lyric.user.user_profile.icon.url, class: "rounded-circle", size: "25x25") %>
            <% else %>
              <%= image_tag("default.png", class: "rounded-circle", size: "25x25") %>
            <% end %>
            <p class="ml-2"><%= favorite.lyric.user.user_profile.name %></p>
          <% end %>
          <span class="ml-2 text-xs text-gray-500"><%= favorite.lyric.created_at.strftime("%Y-%m-%d %H:%M") %></span>
        </div>
        <p class="px-3 py-2 bg-gray-100 rounded-full text-base text-gray-600"><%= favorite.lyric.phrase %></p>
        <p class="mr-4 ml-4 mt-4 text-gray-600"><%= favorite.lyric.detail %></p>
        <p class="mt-2 mr-2 ml-2 text-gray-600"><%= favorite.lyric.song.title %> / <%= favorite.lyric.artist.name %></p>
        <p  class="mt-4 mb-4">
          <% favorite.lyric.feelings.each do |feeling| %>
            <span class="tag-pink px-2 py-1 rounded-full text-sm text-gray-500">
              <%= feeling.sort %>
            </span>
          <% end %>
        </p>
        <p class="mb-4"><%= link_to t('view.lyric.show'), lyric_path(favorite.lyric.id) %></p>
      </div>
    <% end %>
  <% else %>
    <p class="text-gray-500 mt-4 text-center">お気に入りした投稿はありません。</p>
  <% end %>
</div>

app/views/users/show_followers.html.erb
<div class="container mx-auto py-8">
  <h2 class="text-2xl mb-4 text-gray-600"><%= @user.user_profile.name %>のフォロワー一覧</h2>
  <% if @followers.any? %>
    <div class="grid grid-cols-1 gap-4">
      <% @followers.each do |follower| %>
        <div class="w-64 mx-auto bg-white shadow-md rounded-lg p-4">
          <%= link_to user_path(follower.id) do %>
            <% if follower.user_profile.icon && follower.user_profile.icon.url %>
              <%= image_tag(follower.user_profile.icon.url, class: "rounded-full w-12 h-12 mx-auto") %>
            <% else %>
              <%= image_tag("default.png", class: "rounded-full w-12 h-12 mx-auto") %>
            <% end %>
          <span class="block text-center mt-2"><%= follower.user_profile.name %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-500 mt-4 text-center">フォロワーはまだいません。</p>
  <% end %>
</div>

app/views/users/show_following.html.erb
<div class="container mx-auto py-8">
  <h2 class="text-2xl mb-4 text-gray-600"><%= @user.user_profile.name %>がフォローしている<br>ユーザー一覧</h2>

  <% if @following.any? %>
    <div class="grid grid-cols-1 gap-4">
      <% @following.each do |following| %>
        <div class="w-64 mx-auto bg-white shadow-md rounded-lg p-4">
          <%= link_to user_path(following.id) do %>
            <% if following.user_profile.icon && following.user_profile.icon.url %>
              <%= image_tag(following.user_profile.icon.url, class: "rounded-full w-12 h-12 mx-auto") %>
            <% else %>
              <%= image_tag("default.png", class: "rounded-full w-12 h-12 mx-auto") %>
            <% end %>
          <span class="block text-center mt-2"><%= following.user_profile.name %></span>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-gray-500 mt-4 text-center">フォローしているユーザーはいません。</p>
  <% end %>
</div>