config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root 'homes#index'
  resources :homes, only: :index

  get '/lyrics/ranking', to: 'lyrics#ranking'
  resources :lyrics, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:index]
    member do
      get :explain
    end
  end

  resources :users, only: [:show] do
    member do
      get :favorites, to: 'users#show_favorites', as: 'user_favorites'
      get :show_followers
      get :show_following
    end
  end

  post '/users/guest_sign_in', to: 'users#guest_sign_in'
  post '/users/guest_admin_sign_in', to: 'users#guest_admin_sign_in'

  resources :favorites, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  belongs_to :lyric
  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :lyric
  belongs_to :user
  validates :content, presence: true
  has_many :notifications, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :lyric
end

app/models/feeling.rb
class Feeling < ApplicationRecord
  has_many :lyrics_feelings, dependent: :destroy
  has_many :lyrics, through: :lyrics_feelings, source: :lyric
  validates :sort, presence: true
  def self.ransackable_attributes(auth_object = nil)
    %w[id sort]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[lyrics lyrics_feelings]
  end
end

app/models/lyric.rb
class Lyric < ApplicationRecord
  validates :phrase, presence: true, length: { maximum: 20 }
  validates :detail, presence: true
  has_one :artist, dependent: :destroy
  has_one :song, dependent: :destroy
  accepts_nested_attributes_for :artist, allow_destroy: true
  accepts_nested_attributes_for :song, allow_destroy: true
  belongs_to :user
  has_many :lyrics_feelings, dependent: :destroy
  has_many :feelings, through: :lyrics_feelings, source: :feeling
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  is_impressionable counter_cache: true
  validates :phrase, presence: true
  validates :detail, presence: true

  scope :recently_created, -> { where('created_at >= ?', 1.month.ago) }
  scope :ranked, -> { order(impressions_count: :desc) }
  scope :with_associations, -> { includes(:song, :artist, :comments, user: :user_profile) }

  def self.ransackable_attributes(auth_object = nil)
    %w[id phrase]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[artist song feelings lyrics_feelings]
  end

  def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and lyric_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        lyric_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(lyric_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      lyric_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/lyrics_feeling.rb
class LyricsFeeling < ApplicationRecord
  belongs_to :lyric
  belongs_to :feeling
  def self.ransackable_attributes(auth_object = nil)
    %w[lyric_id feeling_id]
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :lyric, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :lyric
  validates :title, presence: true

  def self.ransackable_attributes(auth_object = nil)
    %w[title]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :timeoutable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :user_profile, dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :user_profile
  has_many :lyrics
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_lyrics, through: :favorites, source: :lyric
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.build_user_profile(name: "ゲスト")
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'guest-admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.build_user_profile(name: "ゲスト(管理者)")
      user.admin = true
    end
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user, inverse_of: :user_profile
  mount_uploader :icon, ImageUploader
  validates :name, presence: true
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lyrics_helper.rb
module LyricsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavLyri</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
  </head>
  <body>
  <header>
    <%= link_to image_tag("logo-fav-lyri.png", class: "rounded-circle", size: "70x70"), lyrics_path %>
    <% if user_signed_in? %>
      <%= link_to user_path(current_user.id) do %>
        <% if current_user.user_profile.icon && current_user.user_profile.icon.url %>
          <%= image_tag(current_user.user_profile.icon.url, class: "rounded-circle nav-icon", size: "35x35") %>
        <% else %>
          <%= image_tag("default.png", class: "rounded-circle nav-icon", size: "35x35") %>
        <% end %>
      <% end %>
      <%= link_to new_lyric_path do %>
        <%= image_tag("pen.png", class: "rounded-circle nav-icon", size: "25x25") %>
      <% end %>
      <%= link_to notifications_path do %>
        <% if @unchecked_notifications.any? %>
          <%= image_tag("bell ringing.png", class: "rounded-circle nav-icon", size: "20x20") %>
        <% else %>
          <%= image_tag("bell.png", class: "rounded-circle nav-icon", size: "20x20") %>
        <% end %>
      <% end %>
      <%= link_to t('view.navigation.about'), root_path %>
      <%= link_to t('view.navigation.logout'), destroy_user_session_path, method: :delete %>
      <% if current_user.admin == true %>
        <%= link_to t('view.navigation.admin_page'), rails_admin_path %>
      <% end %>
    <% else %>
      <%= link_to t('view.navigation.about'), root_path %>
      <%= link_to t('view.navigation.login'), new_user_session_path %>
      <%= link_to t('view.navigation.guest_login'), users_guest_sign_in_path, method: :post %>
      <%= link_to t('view.navigation.guest_admin_login'), users_guest_admin_sign_in_path, method: :post %>
    <% end %>
  </header>
  <div class="text-center pt-20 mt-10">
    <% if notice %>
      <p class="notice tag-pink text-gray-500 px-4 py-3 mb-4 rounded-lg max-w-md inline-block"><%= notice %></p>
    <% end %>
    <br>
    <% if alert %>
      <p class="alert bg-red-100 text-red-600 px-4 py-3 mb-4 rounded-lg max-w-md inline-block"><%= alert %></p>
    <% end %>
  </div>
  <%= yield %>
  <footer class="footer mt-10">
    <span class="block text-xs text-gray-500 sm:text-center dark:text-gray-400">Copyright &copy;2023 by Mikiko Kanda. All rights reserved.</span>
  </footer>
</body>
</html>